source 'https://github.com/CocoaPods/Specs.git'

target 'AWNibWrapper', :exclusive => true do
  pod "AWNibWrapper", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AWNibWrapper", :path => "../"

  
end
